@startuml SpeedCalculator

class SpeedCalculator {

    +speedChange(acceleration: Acceleration, attitude: Attitude, timeInterval: Double)
}
SpeedCalculator --> MotionManagerProtocol: -motionManager

@enduml